# Writes dist/faxal.c: the whole language runtime as ONE C file.
#
#   cc -O2 -o faxal faxal.c -lm        (Linux, macOS)
#   gcc -O2 -o faxal.exe faxal.c       (Windows with MinGW-w64)
#
# That single command is all it takes to build faxal on a machine that has nothing but a C compiler:
# no Make, no Python, no Node, and nothing to download. The compiler, the standard library and the
# tools inside the result are Faxal programs that were compiled to bytecode beforehand (embedded.c),
# so the result starts as a complete, self-hosted faxal.
#
# This tool is written in Faxal. Run it with:  make amalgam

let out_path = os.args.len() > 0 and os.args[0] or "dist/faxal.c"
let order = ["platform.h", "faxal.h", "core.c", "compiler.c", "bytecode.c", "selfhost.c", "debug.c", "vm.c", "stdlib.c", "bundle.c", "embedded.c", "main.c"]
let included = {}
let out = [
  "/* faxal " + "single-file build, generated by tools/amalgamate.fx. Do not edit: edit native/src and run `make amalgam`. */",
]

fn include_file(name) {
  if included.has(name) { return }
  included[name] = true
  out.push("")
  out.push("/* ======================================================== " + name + " */")
  for line in fs.read("src/" + name).lines() {
    let t = line.trim()
    if t.starts_with("#include \"") {
      include_file(t[10:t.find("\"", 10)])
    } else {
      out.push(line)
    }
  }
}

for name in order { include_file(name) }
let count = len(fs.list("src"))
if count != order.len() { throw "src/ has " + str(count) + " files but amalgamate.fx lists " + str(order.len()) + ": update the list" }

let slash = out_path.reverse().find("/")
if slash >= 0 {
  let dir = out_path[0:len(out_path) - slash - 1]
  if dir != "" and not fs.exists(dir) { fs.mkdir(dir) }
}
fs.write(out_path, out.join("\n") + "\n")
print("wrote " + out_path + ": " + str(len(out)) + " lines")
