# Generates src/embedded.c: every Faxal file in lib/ (the standard library, the compiler, the tools),
# compiled to bytecode and built into the faxal program as C arrays. That is how faxal starts without
# compiling anything: its own compiler is already inside it, ready to run. This tool is written in
# Faxal, so faxal builds its own library. Run it with:  make embed
#
# Each file is compiled with the compiler written in C (--c-compiler), which is the fixed starting
# point of the build. The Faxal compiler writes exactly the same bytes (see tests/bytecode_check.py).

let out_path = os.args.len() > 0 and os.args[0] or "src/embedded.c"
let binary = os.env("FAXAL") ?? "bin/faxal"
let files = []

fn walk(dir, prefix) {
  for name in fs.list(dir) {
    let path = dir + "/" + name
    if fs.is_dir(path) {
      walk(path, prefix + name + "/")
    } else if name.ends_with(".fx") {
      files.push([prefix + name[:-3], path])
    }
  }
}

# Quote text for the shell.
fn q(s) { return "'" + s.replace("'", "'\\''") + "'" }

walk("lib", "")
files.sort(fn(a, b) {
  if a[0] < b[0] { return -1 }
  if a[0] > b[0] { return 1 }
  return 0
})

let out = [
  "/* Generated by tools/embed.fx. Do not edit. */",
  "#include \"faxal.h\"",
  "",
]
let table = []
for i in 0..files.len() {
  let symbol = "embedded_" + i
  let r = os.run(q(binary) + " --c-compiler compile --emit-c " + symbol + " " + q(files[i][1]))
  if r.code != 0 { throw "could not compile " + files[i][1] + ":\n" + r.output }
  out.push("/* " + files[i][0] + " */")
  out.push(r.output.trim())
  out.push("")
  table.push("  {\"" + files[i][0] + "\", " + symbol + ", sizeof " + symbol + "},")
}
out.push("const EmbeddedFile embeddedFiles[] = {")
for line in table { out.push(line) }
out.push("  {NULL, NULL, 0}")
out.push("};")
out.push("const int embeddedCount = " + len(files) + ";")

fs.write(out_path, out.join("\n") + "\n")
print(f"wrote {out_path}: {len(files)} Faxal files embedded as bytecode")
